# Generated by Django 5.0.1 on 2024-02-01 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновление')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наиминование')),
                ('full_name', models.CharField(max_length=200, unique=True, verbose_name='Полное наиминование')),
                ('phone_number', models.CharField(max_length=200, unique=True, verbose_name='Номер телефона')),
                ('inn', models.CharField(max_length=200, unique=True, verbose_name='ИНН')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновление')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрегенты',
            },
        ),
        migrations.CreateModel(
            name='OperationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.SmallIntegerField(choices=[(0, 'Расход'), (1, 'Приход')], verbose_name='Действие')),
                ('status', models.SmallIntegerField(choices=[(0, 'На расмотрения'), (1, 'Принята')], default=0, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновление')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbor.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Группа Операция',
                'verbose_name_plural': 'Группа Операции',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изоброжение')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновление')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbor.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Ценна')),
                ('discount', models.FloatField(verbose_name='Акция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновление')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbor.operationgroup', verbose_name='Группа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anbor.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
    ]
